name: Lint

on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true
      name:
        type: string
        required: true
      command:
        type: string
        required: true

jobs:
  lint:
    name: ${{ inputs.name }}
    runs-on: ubuntu-20.04
    container:
      image: ${{ inputs.image }}
      options: "--user=root:root"

    steps:
      - name: Execute ${{ inputs.command }}
        run: ${{ inputs.command }}
        working-directory: /rails
