name: Release

on:
  workflow_call:
    inputs:
      reference:
        type: string
        required: false
        default: main
      tag:
        type: string
        required: true

jobs:
  release:
    name: Create release page
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          tag: ${{ inputs.tag }}
          commit: ${{ inputs.reference }}
