name: Tag application

on:
  workflow_call:
    inputs:
      reference:
        type: string
        required: false
        default: main
    outputs:
      version:
        description: Prefix of image name
        value: ${{ jobs.tag.outputs.version }}

jobs:
  tag:
    name: Determine tag number
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semver.outputs.next }}
      branch: ${{ inputs.reference }}

    steps:
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          noVersionBumpBehavior: patch
          branch: main
          majorList: "BREAK"
          minorList: "NEW"
          patchList: "FIX,OPT"
